/** Auto-generated from public/background/background-conf-room/ – do not edit manually */

export const CONFERENCE_BACKGROUND_SLIDES = [
  '/background/background-conf-room/bg1.jpg',
  '/background/background-conf-room/bg-5.jpg',
  '/background/background-conf-room/bg-7.jpg',
  '/background/background-conf-room/bg-10.jpg',
  '/background/background-conf-room/bg-3.jpg',
  '/background/background-conf-room/bg-18.jpg',
  '/background/background-conf-room/bg-4.jpg',
  '/background/background-conf-room/cpt-art-1.jpg',
  '/background/background-conf-room/bg-17.jpg',
  '/background/background-conf-room/bg-12.jpg',
  '/background/background-conf-room/bg-9.jpg',
  '/background/background-conf-room/bg-24.jpg',
  '/background/background-conf-room/bg-6.jpg',
  '/background/background-conf-room/bg-14.jpg',
  '/background/background-conf-room/bg-13.jpg',
  '/background/background-conf-room/bg-21.jpg',
  '/background/background-conf-room/br-aRT-2.jpg',
  '/background/background-conf-room/bg-20.jpg',
  '/background/background-conf-room/bg-8.jpg',
  '/background/background-conf-room/bg-15.jpg',
  '/background/background-conf-room/cpr-art-dark-1.jpg',
  '/background/background-conf-room/bg-23.jpg',
  '/background/background-conf-room/bg-25.jpg',
  '/background/background-conf-room/bg-22.jpg',
  '/background/background-conf-room/bg-11.jpg',
  '/background/background-conf-room/bg-19.jpg',
] as const;
