/** Auto-generated from public/backgrounds/jackies-cute-backgrounds/ – do not edit manually */

export const JACKIES_BACKGROUND_SLIDES = [
  '/backgrounds/jackies-cute-backgrounds/x3.jpg',
  '/backgrounds/jackies-cute-backgrounds/j16.jpg',
  '/backgrounds/jackies-cute-backgrounds/c2.jpg',
  '/backgrounds/jackies-cute-backgrounds/x7.jpg',
  '/backgrounds/jackies-cute-backgrounds/j6.jpg',
  '/backgrounds/jackies-cute-backgrounds/x8.jpg',
  '/backgrounds/jackies-cute-backgrounds/c8.jpg',
  '/backgrounds/jackies-cute-backgrounds/j2.jpg',
  '/backgrounds/jackies-cute-backgrounds/j5.jpg',
  '/backgrounds/jackies-cute-backgrounds/j18.jpg',
  '/backgrounds/jackies-cute-backgrounds/j4.jpg',
  '/backgrounds/jackies-cute-backgrounds/j8.jpg',
  '/backgrounds/jackies-cute-backgrounds/j20.jpg',
  '/backgrounds/jackies-cute-backgrounds/x1.jpg',
  '/backgrounds/jackies-cute-backgrounds/w2.jpg',
  '/backgrounds/jackies-cute-backgrounds/x12.jpg',
  '/backgrounds/jackies-cute-backgrounds/j7.jpg',
  '/backgrounds/jackies-cute-backgrounds/x2.jpg',
  '/backgrounds/jackies-cute-backgrounds/x6.jpg',
  '/backgrounds/jackies-cute-backgrounds/x10.jpg',
  '/backgrounds/jackies-cute-backgrounds/c1.jpg',
  '/backgrounds/jackies-cute-backgrounds/x5.jpg',
  '/backgrounds/jackies-cute-backgrounds/x11.jpg',
  '/backgrounds/jackies-cute-backgrounds/x9.jpg',
  '/backgrounds/jackies-cute-backgrounds/x14.jpg',
  '/backgrounds/jackies-cute-backgrounds/c5.jpg',
  '/backgrounds/jackies-cute-backgrounds/j1.jpg',
  '/backgrounds/jackies-cute-backgrounds/j3.jpg',
  '/backgrounds/jackies-cute-backgrounds/j14.jpg',
  '/backgrounds/jackies-cute-backgrounds/j17.jpg',
  '/backgrounds/jackies-cute-backgrounds/j11.jpg',
  '/backgrounds/jackies-cute-backgrounds/w1.jpg',
  '/backgrounds/jackies-cute-backgrounds/j12.jpg',
  '/backgrounds/jackies-cute-backgrounds/x13.jpg',
  '/backgrounds/jackies-cute-backgrounds/j15.jpg',
  '/backgrounds/jackies-cute-backgrounds/c3.jpg',
  '/backgrounds/jackies-cute-backgrounds/w3.jpg',
  '/backgrounds/jackies-cute-backgrounds/j19.jpg',
  '/backgrounds/jackies-cute-backgrounds/cc4.jpg',
  '/backgrounds/jackies-cute-backgrounds/j9.jpg',
  '/backgrounds/jackies-cute-backgrounds/j10.jpg',
  '/backgrounds/jackies-cute-backgrounds/j13.jpg',
] as const;
