/** Auto-generated from public/backgrounds/julies-unicorns/ – do not edit manually */

export const JULIES_BACKGROUND_SLIDES = [
  '/backgrounds/julies-unicorns/u-color-7.jpg',
  '/backgrounds/julies-unicorns/j22.jpg',
  '/backgrounds/julies-unicorns/j4.jpg',
  '/backgrounds/julies-unicorns/u-color-9.jpg',
  '/backgrounds/julies-unicorns/j24.jpg',
  '/backgrounds/julies-unicorns/u2.jpg',
  '/backgrounds/julies-unicorns/u-color-6.jpg',
  '/backgrounds/julies-unicorns/j1`7.jpg',
  '/backgrounds/julies-unicorns/j10.jpg',
  '/backgrounds/julies-unicorns/j17.jpg',
  '/backgrounds/julies-unicorns/j16.jpg',
  '/backgrounds/julies-unicorns/adorable-pink-unicorn-with-stars.png',
  '/backgrounds/julies-unicorns/j8.jpg',
  '/backgrounds/julies-unicorns/j14.jpg',
  '/backgrounds/julies-unicorns/u1.jpg',
  '/backgrounds/julies-unicorns/u-color-3.jpg',
  '/backgrounds/julies-unicorns/j5.jpg',
  '/backgrounds/julies-unicorns/u-color-10.jpg',
  '/backgrounds/julies-unicorns/j11.jpg',
  '/backgrounds/julies-unicorns/u-color-12.jpg',
  '/backgrounds/julies-unicorns/j13.jpg',
  '/backgrounds/julies-unicorns/j18.jpg',
  '/backgrounds/julies-unicorns/j2.jpg',
  '/backgrounds/julies-unicorns/u-color-1.jpg',
  '/backgrounds/julies-unicorns/j6.jpg',
  '/backgrounds/julies-unicorns/j23.jpg',
  '/backgrounds/julies-unicorns/7466821.jpg',
  '/backgrounds/julies-unicorns/j12.jpg',
  '/backgrounds/julies-unicorns/j3.jpg',
  '/backgrounds/julies-unicorns/u-color-11.jpg',
  '/backgrounds/julies-unicorns/u-color-5.jpg',
  '/backgrounds/julies-unicorns/j9.jpg',
  '/backgrounds/julies-unicorns/u-color-2.jpg',
  '/backgrounds/julies-unicorns/u-color-8.jpg',
  '/backgrounds/julies-unicorns/j7.jpg',
  '/backgrounds/julies-unicorns/j19.jpg',
  '/backgrounds/julies-unicorns/j1.jpg',
  '/backgrounds/julies-unicorns/u-color-4.jpg',
  '/backgrounds/julies-unicorns/j20.jpg',
  '/backgrounds/julies-unicorns/j21.jpg',
  '/backgrounds/julies-unicorns/j15.jpg',
] as const;
